/*
 * THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * Copyright (C) 2023 Trusted Objects. All rights reserved.
 */

#ifndef _TO_CMDS_IDENTIFIERS_H_
#define _TO_CMDS_IDENTIFIERS_H_

#include <stdint.h>

typedef enum command_identifiers_e {
	TO_CMD_ID_RES						= 0x0000,
	TO_CMD_ID_GET_SN					= 0x0001,
	TO_CMD_ID_GET_PN					= 0x0002,
	TO_CMD_ID_GET_HW_VERSION				= 0x0003,
	TO_CMD_ID_GET_SW_VERSION				= 0x0004,
	TO_CMD_ID_GET_RANDOM					= 0x0005,
	TO_CMD_ID_GET_CERTIFICATE				= 0x0006,
	TO_CMD_ID_SIGN						= 0x0007,
	TO_CMD_ID_GET_CERTIFICATE_AND_SIGN			= 0x0008,
	TO_CMD_ID_VERIFY_CERTIFICATE_AND_STORE			= 0x0009,
	TO_CMD_ID_GET_CHALLENGE_AND_STORE			= 0x000A,
	TO_CMD_ID_VERIFY_CHALLENGE_SIGNATURE			= 0x000B,
	TO_CMD_ID_COMPUTE_HMAC					= 0x000C,
	TO_CMD_ID_VERIFY_HMAC					= 0x000D,
	TO_CMD_ID_AES128CBC_ENCRYPT				= 0x000E,
	TO_CMD_ID_AES128CBC_DECRYPT				= 0x000F,
	TO_CMD_ID_ECHO						= 0x0010,
	TO_CMD_ID_SLEEP						= 0x0011,
	TO_CMD_ID_VERIFY					= 0x0012,
	TO_CMD_ID_SET_PRE_PERSONALIZATION_DATA			= 0x0013,
	TO_CMD_ID_ADMIN_COMMAND					= 0x0014,
	TO_CMD_ID_SET_NEXT_STATE				= 0x0015,
	TO_CMD_ID_GET_STATE					= 0x0016,
	TO_CMD_ID_LOCK						= 0x0017,
	TO_CMD_ID_UNLOCK					= 0x0018,
	TO_CMD_ID_GET_KEY_FINGERPRINT				= 0x0019,
	TO_CMD_ID_COMPUTE_CMAC					= 0x001C,
	TO_CMD_ID_VERIFY_CMAC					= 0x001D,
	TO_CMD_ID_SIGN_HASH					= 0x001E,
	TO_CMD_ID_VERIFY_HASH_SIGNATURE				= 0x001F,
	TO_CMD_ID_AES128CBC_IV_ENCRYPT				= 0x0020,
	TO_CMD_ID_READ_NVM					= 0x0021,
	TO_CMD_ID_WRITE_NVM					= 0x0022,
	TO_CMD_ID_COMPUTE_HMAC_INIT				= 0x0023,
	TO_CMD_ID_COMPUTE_HMAC_UPDATE				= 0x0024,
	TO_CMD_ID_COMPUTE_HMAC_FINAL				= 0x0025,
	TO_CMD_ID_VERIFY_HMAC_INIT				= 0x0026,
	TO_CMD_ID_VERIFY_HMAC_UPDATE				= 0x0027,
	TO_CMD_ID_VERIFY_HMAC_FINAL				= 0x0028,
	TO_CMD_ID_TLS_GET_RANDOM_AND_STORE			= 0x0029,
	TO_CMD_ID_TLS_RENEW_KEYS				= 0x002A,
	TO_CMD_ID_GET_TLS_MASTER_SECRET				= 0x002B,
	TO_CMD_ID_TLS_SET_SERVER_EPUBLIC_KEY			= 0x002C,
	TO_CMD_ID_TLS_RENEW_KEYS_ECDHE				= 0x002D,
	TO_CMD_ID_GET_UNSIGNED_PUBLIC_KEY			= 0x002E,
	TO_CMD_ID_TLS_SET_SERVER_RANDOM				= 0x002F,
	TO_CMD_ID_AES128GCM_ENCRYPT				= 0x0030,
	TO_CMD_ID_TLS_CALCULATE_FINISHED			= 0x0031,
	TO_CMD_ID_TLS_GET_CLIENT_HELLO				= 0x0032,
	TO_CMD_ID_TLS_HANDLE_SERVER_HELLO			= 0x0033,
	TO_CMD_ID_AES128GCM_DECRYPT				= 0x0034,
	TO_CMD_ID_TLS_HANDLE_SERVER_KEY_EXCHANGE		= 0x0035,
	TO_CMD_ID_TLS_HANDLE_CERTIFICATE_REQUEST		= 0x0036,
	TO_CMD_ID_TLS_HANDLE_SERVER_HELLO_DONE			= 0x0037,
	TO_CMD_ID_TLS_GET_CERTIFICATE				= 0x0038,
	TO_CMD_ID_TLS_GET_CLIENT_KEY_EXCHANGE			= 0x0039,
	TO_CMD_ID_TLS_GET_CERTIFICATE_VERIFY			= 0x003A,
	TO_CMD_ID_TLS_GET_CHANGE_CIPHER_SPEC			= 0x003B,
	TO_CMD_ID_TLS_GET_FINISHED				= 0x003C,
	TO_CMD_ID_TLS_HANDLE_CHANGE_CIPHER_SPEC			= 0x003D,
	TO_CMD_ID_TLS_HANDLE_FINISHED				= 0x003E,
	TO_CMD_ID_TLS_SECURE_MESSAGE				= 0x003F,
	TO_CMD_ID_TLS_UNSECURE_MESSAGE				= 0x0040,
	TO_CMD_ID_TLS_HANDLE_HELLO_VERIFY_REQUEST		= 0x0041,
	TO_CMD_ID_TLS_SET_MODE					= 0x0042,
	TO_CMD_ID_TLS_HANDLE_SERVER_CERTIFICATE_INIT		= 0x0043,
	TO_CMD_ID_TLS_HANDLE_SERVER_CERTIFICATE_UPDATE		= 0x0044,
	TO_CMD_ID_TLS_HANDLE_SERVER_CERTIFICATE_FINAL		= 0x0045,
	TO_CMD_ID_GET_CERTIFICATE_SUBJECT_CN			= 0x0046,
	TO_CMD_ID_VERIFY_CA_CERTIFICATE_AND_STORE		= 0x0047,
	TO_CMD_ID_GET_PRODUCT_ID				= 0x0048,
	TO_CMD_ID_INIT_ADMIN_SESSION				= 0x0049,
	TO_CMD_ID_AUTH_ADMIN_SESSION				= 0x004A,
	TO_CMD_ID_FINI_ADMIN_SESSION				= 0x004B,
	TO_CMD_ID_AES128CCM_ENCRYPT				= 0x004C,
	TO_CMD_ID_AES128CCM_DECRYPT				= 0x004D,
	TO_CMD_ID_AES128ECB_ENCRYPT				= 0x004E,
	TO_CMD_ID_AES128ECB_DECRYPT				= 0x004F,
	TO_CMD_ID_GET_NVM_SIZE					= 0x0050,
	TO_CMD_ID_TLS_SET_CONFIG				= 0x0051,
	TO_CMD_ID_ADMIN_COMMAND_WITH_RESPONSE			= 0x0052,
	TO_CMD_ID_ADMIN_SET_SLOT				= 0x0053,
	TO_CMD_ID_TLS_HANDLE_SERVER_CERTIFICATE			= 0x0054,
	TO_CMD_ID_SET_CERTIFICATE_SIGNING_REQUEST_DN		= 0x0055,
	TO_CMD_ID_GET_CERTIFICATE_SIGNING_REQUEST		= 0x0056,
	TO_CMD_ID_SET_CERTIFICATE				= 0x0057,
	TO_CMD_ID_TLS_HANDLE_MEDIATOR_CERTIFICATE		= 0x0058,
	TO_CMD_ID_TLS_GET_CERTIFICATE_SLOT			= 0x0059,
	TO_CMD_ID_TLS_HANDLE_SERVER_KEY_EXCHANGE_INIT		= 0x005A,
	TO_CMD_ID_TLS_HANDLE_SERVER_KEY_EXCHANGE_UPDATE		= 0x005B,
	TO_CMD_ID_TLS_HANDLE_SERVER_KEY_EXCHANGE_FINAL		= 0x005C,
	TO_CMD_ID_SET_CERTIFICATE_INIT				= 0x005D,
	TO_CMD_ID_SET_CERTIFICATE_UPDATE			= 0x005E,
	TO_CMD_ID_SET_CERTIFICATE_FINAL				= 0x005F,
	TO_CMD_ID_GET_CERTIFICATE_INIT				= 0x0060,
	TO_CMD_ID_GET_CERTIFICATE_UPDATE			= 0x0061,
	TO_CMD_ID_GET_CERTIFICATE_FINAL				= 0x0062,
	TO_CMD_ID_TLS_GET_CLIENT_HELLO_INIT			= 0x0063,
	TO_CMD_ID_TLS_GET_CLIENT_HELLO_UPDATE			= 0x0064,
	TO_CMD_ID_TLS_GET_CLIENT_HELLO_FINAL			= 0x0065,
	TO_CMD_ID_TLS_HANDLE_SERVER_HELLO_INIT			= 0x0066,
	TO_CMD_ID_TLS_HANDLE_SERVER_HELLO_UPDATE		= 0x0067,
	TO_CMD_ID_TLS_HANDLE_SERVER_HELLO_FINAL			= 0x0068,
	TO_CMD_ID_TLS_GET_MASTER_SECRET_DERIVED_KEYS		= 0x006B,
	TO_CMD_ID_GET_CERTIFICATE_X509				= 0x006C,
	TO_CMD_ID_SET_CERTIFICATE_X509				= 0x006D,
	TO_CMD_ID_GET_CERTIFICATE_SHORT				= 0x006E,
	TO_CMD_ID_GET_CERTIFICATE_STANDALONE			= 0x006F,
	TO_CMD_ID_ACCESS_DUMMY_DATA				= 0x0070,
	TO_CMD_ID_AES128CBC_HMAC_SECURE_MESSAGE			= 0x00A0,
	TO_CMD_ID_AES128CBC_HMAC_UNSECURE_MESSAGE		= 0x00A1,
	TO_CMD_ID_SHA256					= 0x00A2,
	TO_CMD_ID_SET_REMOTE_PUBLIC_KEY				= 0x00A3,
	TO_CMD_ID_RENEW_ECC_KEYS				= 0x00A4,
	TO_CMD_ID_GET_PUBLIC_KEY				= 0x00A5,
	TO_CMD_ID_RENEW_SHARED_KEYS				= 0x00A6,
	TO_CMD_ID_SET_AES_KEY					= 0x00A7,
	TO_CMD_ID_SET_HMAC_KEY					= 0x00A8,
	TO_CMD_ID_SET_CMAC_KEY					= 0x00A9,
	TO_CMD_ID_SHA256_INIT					= 0x00AA,
	TO_CMD_ID_SHA256_UPDATE					= 0x00AB,
	TO_CMD_ID_SHA256_FINAL					= 0x00AC,
	TO_CMD_ID_VERIFY_CHAIN_CERTIFICATE_AND_STORE_INIT	= 0x00AD,
	TO_CMD_ID_VERIFY_CHAIN_CERTIFICATE_AND_STORE_UPDATE	= 0x00AE,
	TO_CMD_ID_VERIFY_CHAIN_CERTIFICATE_AND_STORE_FINAL	= 0x00AF,
	TO_CMD_ID_GET_HW_SN					= 0x00B0,
	TO_CMD_ID_SET_STATUS_PIO_CONFIG				= 0x00B1,
	TO_CMD_ID_GET_STATUS_PIO_CONFIG				= 0x00B2,
	TO_CMD_ID_VERIFY_CHAIN_CA_CERTIFICATE_AND_STORE_INIT	= 0x00B3,
	TO_CMD_ID_VERIFY_CHAIN_CA_CERTIFICATE_AND_STORE_UPDATE	= 0x00B4,
	TO_CMD_ID_VERIFY_CHAIN_CA_CERTIFICATE_AND_STORE_FINAL	= 0x00B5,
	TO_CMD_ID_TLS_RESET					= 0x00B6,
	TO_CMD_ID_TLS_SECURE_MESSAGE_INIT			= 0x00B7,
	TO_CMD_ID_TLS_SECURE_MESSAGE_UPDATE			= 0x00B8,
	TO_CMD_ID_TLS_SECURE_MESSAGE_FINAL			= 0x00B9,
	TO_CMD_ID_TLS_UNSECURE_MESSAGE_INIT			= 0x00BA,
	TO_CMD_ID_TLS_UNSECURE_MESSAGE_UPDATE			= 0x00BB,
	TO_CMD_ID_TLS_UNSECURE_MESSAGE_FINAL			= 0x00BC,
	TO_CMD_ID_TLS_GET_CERTIFICATE_INIT			= 0x00BD,
	TO_CMD_ID_TLS_GET_CERTIFICATE_UPDATE			= 0x00BE,
	TO_CMD_ID_TLS_GET_CERTIFICATE_FINAL			= 0x00BF,
	TO_CMD_ID_TLS_SET_SESSION				= 0x00C0,
	TO_CMD_ID_AES128CBC_CMAC_SECURE_MESSAGE			= 0x00C1,
	TO_CMD_ID_AES128CBC_CMAC_UNSECURE_MESSAGE		= 0x00C2,
	TO_CMD_ID_SECURE_MESSAGE				= 0x00C3,
	TO_CMD_ID_SECURE_MESSAGE_INIT				= 0x00C4,
	TO_CMD_ID_SECURE_MESSAGE_UPDATE				= 0x00C5,
	TO_CMD_ID_SECURE_MESSAGE_FINAL				= 0x00C6,
	TO_CMD_ID_UNSECURE_MESSAGE				= 0x00C7,
	TO_CMD_ID_UNSECURE_MESSAGE_INIT				= 0x00C8,
	TO_CMD_ID_UNSECURE_MESSAGE_UPDATE			= 0x00C9,
	TO_CMD_ID_UNSECURE_MESSAGE_FINAL			= 0x00CA,
	TO_CMD_ID_TLS_SET_CONNECTION_ID_EXT_ID			= 0x00CB,
	TO_CMD_ID_DATA_MIGRATION				= 0x00D6,
	TO_CMD_ID_LOADER_BCAST_RESTORE				= 0x00D7,
	TO_CMD_ID_SET_MEASURE_BOOT				= 0x00E0,
	TO_CMD_ID_VALIDATE_NEW_FW_HASH				= 0x00E1,
	TO_CMD_ID_COMMIT_NEW_FW_HASH				= 0x00E2,
	TO_CMD_ID_STORE_NEW_TRUSTED_FW_HASH			= 0x00E3,
	TO_CMD_ID_GET_BOOT_MEASUREMENT				= 0x00E4,
	TO_CMD_ID_INVALIDATE_NEW_HASH				= 0x00E5,
	TO_CMD_ID_GET_SE_MEASUREMENT				= 0x00E6,
	TO_CMD_ID_LORA_GET_JOIN_REQUEST				= 0x0100,
	TO_CMD_ID_LORA_HANDLE_JOIN_ACCEPT			= 0x0101,
	TO_CMD_ID_LORA_SECURE_PHYPAYLOAD			= 0x0102,
	TO_CMD_ID_LORA_UNSECURE_PHYPAYLOAD			= 0x0103,
	TO_CMD_ID_LORA_GET_APPEUI				= 0x0108,
	TO_CMD_ID_LORA_GET_DEVEUI				= 0x0109,
	TO_CMD_ID_LORA_COMPUTE_MIC				= 0x010A,
	TO_CMD_ID_LORA_ENCRYPT_PAYLOAD				= 0x010B,
	TO_CMD_ID_LORA_DECRYPT_JOIN				= 0x010C,
	TO_CMD_ID_LORA_COMPUTE_SHARED_KEYS			= 0x010D,
	TO_CMD_ID_LORA_GET_DEVADDR				= 0x0110,
	TO_CMD_ID_SECLINK_ARC4					= 0xFF00,
	TO_CMD_ID_SECLINK_ARC4_GET_IV				= 0xFF01,
	TO_CMD_ID_SECLINK_AESHMAC				= 0xFF02,
	TO_CMD_ID_SECLINK_AESHMAC_GET_IV			= 0xFF03,
	TO_CMD_ID_SECLINK_ARC4_GET_NEW_KEY			= 0xFF04,
	TO_CMD_ID_SECLINK_AESHMAC_GET_NEW_KEYS			= 0xFF05,
	TO_CMD_ID_INIT						= 0xFF10,
	TO_CMD_ID_GET_DURATION					= 0xFF11,
	TO_CMD_ID_LOADER_BCAST_INITIALIZE_UPGRADE		= 0xFFF2,
	TO_CMD_ID_LOADER_BCAST_WRITE_DATA			= 0xFFF3,
	TO_CMD_ID_LOADER_BCAST_COMMIT_RELEASE			= 0xFFF4,
	TO_CMD_ID_LOADER_BCAST_GET_INFO				= 0xFFFF
	} command_identifiers_t;

// Init
#define TO_SE_CMD_INIT			                            ((uint16_t)TO_CMD_ID_INIT)
#define TO_SE_CMD_GET_DURATION			                    ((uint16_t)TO_CMD_ID_GET_DURATION)

// System
#define TO_SE_CMD_RES		                                    ((uint16_t)TO_CMD_ID_RES)
#define TO_SE_CMD_GET_SN		                            ((uint16_t)TO_CMD_ID_GET_SN)
#define TO_SE_CMD_GET_PN		                            ((uint16_t)TO_CMD_ID_GET_PN)
#define TO_SE_CMD_GET_HW_VERSION		                    ((uint16_t)TO_CMD_ID_GET_HW_VERSION)
#define TO_SE_CMD_GET_SW_VERSION		                    ((uint16_t)TO_CMD_ID_GET_SW_VERSION)
#define TO_SE_CMD_ACCESS_DUMMY_DATA		                    ((uint16_t)TO_CMD_ID_ACCESS_DUMMY_DATA)
#define TO_SE_CMD_GET_PERSO_INFOS		                    ((uint16_t)TO_CMD_ID_GET_PERSO_INFOS)
#define TO_SE_CMD_GET_RANDOM		                            ((uint16_t)TO_CMD_ID_GET_RANDOM)
#define TO_SE_CMD_READ_NVM		                            ((uint16_t)TO_CMD_ID_READ_NVM)
#define TO_SE_CMD_WRITE_NVM		                            ((uint16_t)TO_CMD_ID_WRITE_NVM)
#define TO_SE_CMD_GET_NVM_SIZE		                            ((uint16_t)TO_CMD_ID_GET_NVM_SIZE)
#define TO_SE_CMD_ECHO		                                    ((uint16_t)TO_CMD_ID_ECHO)
#define TO_SE_CMD_SLEEP		                                    ((uint16_t)TO_CMD_ID_SLEEP)
#define TO_SE_CMD_RESTORE_SLD		                            ((uint16_t)TO_CMD_ID_RESTORE_SLD)
#define TO_SE_CMD_RESTORE_SLD_EMERGENCY		                    ((uint16_t)TO_CMD_ID_RESTORE_SLD_EMERGENCY)
#define TO_SE_CMD_GET_RESTORE_SLD_CERTIFICATE_AND_SIGN	            ((uint16_t)TO_CMD_ID_GET_RESTORE_SLD_CERTIFICATE_AND_SIGN)
#define TO_SE_CMD_VERIFY_RESTORE_SLD_CERTIFICATE_AND_STORE          ((uint16_t)TO_CMD_ID_VERIFY_RESTORE_SLD_CERTIFICATE_AND_STORE)
#define TO_SE_CMD_GET_RESTORE_SLD_CHALLENGE_AND_STORE		    ((uint16_t)TO_CMD_ID_GET_RESTORE_SLD_CHALLENGE_AND_STORE)
#define TO_SE_CMD_GET_HW_SN                                         ((uint16_t)TO_CMD_ID_GET_HW_SN)
#define TO_SE_CMD_SET_STATUS_PIO_CONFIG                             ((uint16_t)TO_CMD_ID_SET_STATUS_PIO_CONFIG)
#define TO_SE_CMD_GET_STATUS_PIO_CONFIG                             ((uint16_t)TO_CMD_ID_GET_STATUS_PIO_CONFIG)
#define TO_SE_CMD_GET_PRODUCT_ID                                    ((uint16_t)TO_CMD_ID_GET_PRODUCT_ID)

// Useless
#define TO_SE_CMD_INFO_SLD		                            ((uint16_t)TO_CMD_ID_INFO_SLD)
#define TO_SE_CMD_INIT_UPGRADE_SLD		                    ((uint16_t)TO_CMD_ID_INIT_UPGRADE_SLD)
#define TO_SE_CMD_WRITE_SLD		                            ((uint16_t)TO_CMD_ID_WRITE_SLD)
#define TO_SE_CMD_COMMIT_SLD		                            ((uint16_t)TO_CMD_ID_COMMIT_SLD)

// TO Authentication
#define TO_SE_CMD_SET_CERTIFICATE_SIGNING_REQUEST_DN		    ((uint16_t)TO_CMD_ID_SET_CERTIFICATE_SIGNING_REQUEST_DN)
#define TO_SE_CMD_GET_CERTIFICATE_SIGNING_REQUEST		    ((uint16_t)TO_CMD_ID_GET_CERTIFICATE_SIGNING_REQUEST)
#define TO_SE_CMD_SET_CERTIFICATE		                    ((uint16_t)TO_CMD_ID_SET_CERTIFICATE)
#define TO_SE_CMD_SET_CERTIFICATE_INIT		                    ((uint16_t)TO_CMD_ID_SET_CERTIFICATE_INIT)
#define TO_SE_CMD_SET_CERTIFICATE_UPDATE		            ((uint16_t)TO_CMD_ID_SET_CERTIFICATE_UPDATE)
#define TO_SE_CMD_SET_CERTIFICATE_FINAL		                    ((uint16_t)TO_CMD_ID_SET_CERTIFICATE_FINAL)
#define TO_SE_CMD_GET_CERTIFICATE_INIT		                    ((uint16_t)TO_CMD_ID_GET_CERTIFICATE_INIT)
#define TO_SE_CMD_GET_CERTIFICATE_UPDATE		            ((uint16_t)TO_CMD_ID_GET_CERTIFICATE_UPDATE)
#define TO_SE_CMD_GET_CERTIFICATE_FINAL		                    ((uint16_t)TO_CMD_ID_GET_CERTIFICATE_FINAL)
#define TO_SE_CMD_GET_CERTIFICATE		                    ((uint16_t)TO_CMD_ID_GET_CERTIFICATE)
#define TO_SE_CMD_GET_CERTIFICATE_SHORT		                    ((uint16_t)TO_CMD_ID_GET_CERTIFICATE_SHORT)
#define TO_SE_CMD_GET_CERTIFICATE_STANDALONE	                    ((uint16_t)TO_CMD_ID_GET_CERTIFICATE_STANDALONE)
#define TO_SE_CMD_GET_CERTIFICATE_SUBJECT_CN		            ((uint16_t)TO_CMD_ID_GET_CERTIFICATE_SUBJECT_CN)
#define TO_SE_CMD_SIGN		                                    ((uint16_t)TO_CMD_ID_SIGN)
#define TO_SE_CMD_VERIFY		                            ((uint16_t)TO_CMD_ID_VERIFY)
#define TO_SE_CMD_SIGN_HASH		                            ((uint16_t)TO_CMD_ID_SIGN_HASH)
#define TO_SE_CMD_VERIFY_HASH_SIGNATURE		                    ((uint16_t)TO_CMD_ID_VERIFY_HASH_SIGNATURE)
#define TO_SE_CMD_GET_CERTIFICATE_AND_SIGN		            ((uint16_t)TO_CMD_ID_GET_CERTIFICATE_AND_SIGN)

/* Remote device Authentication */
#define TO_SE_CMD_VERIFY_CERTIFICATE_AND_STORE                      ((uint16_t)TO_CMD_ID_VERIFY_CERTIFICATE_AND_STORE)
#define TO_SE_CMD_VERIFY_CA_CERTIFICATE_AND_STORE                   ((uint16_t)TO_CMD_ID_VERIFY_CA_CERTIFICATE_AND_STORE)
#define TO_SE_CMD_GET_CHALLENGE_AND_STORE                           ((uint16_t)TO_CMD_ID_GET_CHALLENGE_AND_STORE)
#define TO_SE_CMD_VERIFY_CHALLENGE_SIGNATURE                        ((uint16_t)TO_CMD_ID_VERIFY_CHALLENGE_SIGNATURE)
#define TO_SE_CMD_VERIFY_CHAIN_CERTIFICATE_AND_STORE_INIT           ((uint16_t)TO_CMD_ID_VERIFY_CHAIN_CERTIFICATE_AND_STORE_INIT)
#define TO_SE_CMD_VERIFY_CHAIN_CERTIFICATE_AND_STORE_UPDATE         ((uint16_t)TO_CMD_ID_VERIFY_CHAIN_CERTIFICATE_AND_STORE_UPDATE)
#define TO_SE_CMD_VERIFY_CHAIN_CERTIFICATE_AND_STORE_FINAL          ((uint16_t)TO_CMD_ID_VERIFY_CHAIN_CERTIFICATE_AND_STORE_FINAL)
#define TO_SE_CMD_VERIFY_CHAIN_CA_CERTIFICATE_AND_STORE_INIT        ((uint16_t)TO_CMD_ID_VERIFY_CHAIN_CA_CERTIFICATE_AND_STORE_INIT)
#define TO_SE_CMD_VERIFY_CHAIN_CA_CERTIFICATE_AND_STORE_UPDATE      ((uint16_t)TO_CMD_ID_VERIFY_CHAIN_CA_CERTIFICATE_AND_STORE_UPDATE)
#define TO_SE_CMD_VERIFY_CHAIN_CA_CERTIFICATE_AND_STORE_FINAL       ((uint16_t)TO_CMD_ID_VERIFY_CHAIN_CA_CERTIFICATE_AND_STORE_FINAL)

/* HMAC */
#define TO_SE_CMD_COMPUTE_HMAC                                      ((uint16_t)TO_CMD_ID_COMPUTE_HMAC)
#define TO_SE_CMD_COMPUTE_HMAC_INIT                                 ((uint16_t)TO_CMD_ID_COMPUTE_HMAC_INIT)
#define TO_SE_CMD_COMPUTE_HMAC_UPDATE                               ((uint16_t)TO_CMD_ID_COMPUTE_HMAC_UPDATE)
#define TO_SE_CMD_COMPUTE_HMAC_FINAL                                ((uint16_t)TO_CMD_ID_COMPUTE_HMAC_FINAL)
#define TO_SE_CMD_VERIFY_HMAC                                       ((uint16_t)TO_CMD_ID_VERIFY_HMAC)
#define TO_SE_CMD_VERIFY_HMAC_INIT                                  ((uint16_t)TO_CMD_ID_VERIFY_HMAC_INIT)
#define TO_SE_CMD_VERIFY_HMAC_UPDATE                                ((uint16_t)TO_CMD_ID_VERIFY_HMAC_UPDATE)
#define TO_SE_CMD_VERIFY_HMAC_FINAL                                 ((uint16_t)TO_CMD_ID_VERIFY_HMAC_FINAL)

/* CBC + HMAC */
#define TO_SE_CMD_AES128CBC_HMAC_SECURE_MESSAGE                     ((uint16_t)TO_CMD_ID_AES128CBC_HMAC_SECURE_MESSAGE)
#define TO_SE_CMD_AES128CBC_HMAC_UNSECURE_MESSAGE                   ((uint16_t)TO_CMD_ID_AES128CBC_HMAC_UNSECURE_MESSAGE)

/* CBC + CMAC */
#define TO_SE_CMD_AES128CBC_CMAC_SECURE_MESSAGE                     ((uint16_t)TO_CMD_ID_AES128CBC_CMAC_SECURE_MESSAGE)
#define TO_SE_CMD_AES128CBC_CMAC_UNSECURE_MESSAGE                   ((uint16_t)TO_CMD_ID_AES128CBC_CMAC_UNSECURE_MESSAGE)

/* AES (CBC) */
#define TO_SE_CMD_AES128CBC_ENCRYPT                                 ((uint16_t)TO_CMD_ID_AES128CBC_ENCRYPT)
#define TO_SE_CMD_AES128CBC_DECRYPT                                 ((uint16_t)TO_CMD_ID_AES128CBC_DECRYPT)
#define TO_SE_CMD_AES128CBC_IV_ENCRYPT                              ((uint16_t)TO_CMD_ID_AES128CBC_IV_ENCRYPT)

/* AES (GCM) */
#define TO_SE_CMD_AES128GCM_ENCRYPT                                 ((uint16_t)TO_CMD_ID_AES128GCM_ENCRYPT)
#define TO_SE_CMD_AES128GCM_DECRYPT                                 ((uint16_t)TO_CMD_ID_AES128GCM_DECRYPT)

#define TO_SE_CMD_AES128CCM_ENCRYPT                                 ((uint16_t)TO_CMD_ID_AES128CCM_ENCRYPT)
#define TO_SE_CMD_AES128CCM_DECRYPT                                 ((uint16_t)TO_CMD_ID_AES128CCM_DECRYPT)

/* AES (ECB) */
#define TO_SE_CMD_AES128ECB_ENCRYPT                                 ((uint16_t)TO_CMD_ID_AES128ECB_ENCRYPT)
#define TO_SE_CMD_AES128ECB_DECRYPT                                 ((uint16_t)TO_CMD_ID_AES128ECB_DECRYPT)

/* CMAC */
#define TO_SE_CMD_COMPUTE_CMAC 	                                    ((uint16_t)TO_CMD_ID_COMPUTE_CMAC)
#define TO_SE_CMD_VERIFY_CMAC 	                                    ((uint16_t)TO_CMD_ID_VERIFY_CMAC)

/* HASH: SHA256 */
#define TO_SE_CMD_SHA256 		                            ((uint16_t)TO_CMD_ID_SHA256)
#define TO_SE_CMD_SHA256_INIT 	                                    ((uint16_t)TO_CMD_ID_SHA256_INIT)
#define TO_SE_CMD_SHA256_UPDATE 	                            ((uint16_t)TO_CMD_ID_SHA256_UPDATE)
#define TO_SE_CMD_SHA256_FINAL 	                                    ((uint16_t)TO_CMD_ID_SHA256_FINAL)

/* ECIES Key Managment */
#define TO_SE_CMD_SET_REMOTE_PUBLIC_KEY 	                    ((uint16_t)TO_CMD_ID_SET_REMOTE_PUBLIC_KEY)
#define TO_SE_CMD_RENEW_ECC_KEYS 	                            ((uint16_t)TO_CMD_ID_RENEW_ECC_KEYS)
#define TO_SE_CMD_GET_PUBLIC_KEY 	                            ((uint16_t)TO_CMD_ID_GET_PUBLIC_KEY)
#define TO_SE_CMD_GET_UNSIGNED_PUBLIC_KEY 	                    ((uint16_t)TO_CMD_ID_GET_UNSIGNED_PUBLIC_KEY)
#define TO_SE_CMD_RENEW_SHARED_KEYS 	                            ((uint16_t)TO_CMD_ID_RENEW_SHARED_KEYS)
#define TO_SE_CMD_GET_KEY_FINGERPRINT 	                            ((uint16_t)TO_CMD_ID_GET_KEY_FINGERPRINT)
#define TO_SE_CMD_GET_CERTIFICATE_X509                              ((uint16_t)TO_CMD_ID_GET_CERTIFICATE_X509)
#define TO_SE_CMD_SET_CERTIFICATE_X509                              ((uint16_t)TO_CMD_ID_SET_CERTIFICATE_X509)

/* TLS optimized */
#define TO_SE_CMD_TLS_RESET 	                                    ((uint16_t)TO_CMD_ID_TLS_RESET)
#define TO_SE_CMD_TLS_SET_MODE 	                                    ((uint16_t)TO_CMD_ID_TLS_SET_MODE)
#define TO_SE_CMD_TLS_SET_CONFIG 	                            ((uint16_t)TO_CMD_ID_TLS_SET_CONFIG)
#define TO_SE_CMD_TLS_SET_SESSION 	                            ((uint16_t)TO_CMD_ID_TLS_SET_SESSION)
#define TO_SE_CMD_TLS_SET_CONNECTION_ID_EXT_ID 	                    ((uint16_t)TO_CMD_ID_TLS_SET_CONNECTION_ID_EXT_ID)
#define TO_SE_CMD_TLS_GET_CLIENT_HELLO 	                            ((uint16_t)TO_CMD_ID_TLS_GET_CLIENT_HELLO)
#define TO_SE_CMD_TLS_HANDLE_HELLO_VERIFY_REQUEST 	            ((uint16_t)TO_CMD_ID_TLS_HANDLE_HELLO_VERIFY_REQUEST)
#define TO_SE_CMD_TLS_HANDLE_SERVER_HELLO 	                    ((uint16_t)TO_CMD_ID_TLS_HANDLE_SERVER_HELLO)
#define TO_SE_CMD_TLS_HANDLE_SERVER_HELLO_INIT           	    ((uint16_t)TO_CMD_ID_TLS_HANDLE_SERVER_HELLO_INIT)
#define TO_SE_CMD_TLS_HANDLE_SERVER_HELLO_UPDATE         	    ((uint16_t)TO_CMD_ID_TLS_HANDLE_SERVER_HELLO_UPDATE)
#define TO_SE_CMD_TLS_HANDLE_SERVER_HELLO_FINAL          	    ((uint16_t)TO_CMD_ID_TLS_HANDLE_SERVER_HELLO_FINAL)
#define TO_SE_CMD_TLS_HANDLE_SERVER_CERTIFICATE 	            ((uint16_t)TO_CMD_ID_TLS_HANDLE_SERVER_CERTIFICATE)
#define TO_SE_CMD_TLS_HANDLE_SERVER_CERTIFICATE_INIT 	            ((uint16_t)TO_CMD_ID_TLS_HANDLE_SERVER_CERTIFICATE_INIT)
#define TO_SE_CMD_TLS_HANDLE_SERVER_CERTIFICATE_UPDATE 	            ((uint16_t)TO_CMD_ID_TLS_HANDLE_SERVER_CERTIFICATE_UPDATE)
#define TO_SE_CMD_TLS_HANDLE_SERVER_CERTIFICATE_FINAL 	            ((uint16_t)TO_CMD_ID_TLS_HANDLE_SERVER_CERTIFICATE_FINAL)
#define TO_SE_CMD_TLS_HANDLE_SERVER_KEY_EXCHANGE 	            ((uint16_t)TO_CMD_ID_TLS_HANDLE_SERVER_KEY_EXCHANGE)
#define TO_SE_CMD_TLS_HANDLE_SERVER_KEY_EXCHANGE_INIT    	    ((uint16_t)TO_CMD_ID_TLS_HANDLE_SERVER_KEY_EXCHANGE_INIT)
#define TO_SE_CMD_TLS_HANDLE_SERVER_KEY_EXCHANGE_UPDATE  	    ((uint16_t)TO_CMD_ID_TLS_HANDLE_SERVER_KEY_EXCHANGE_UPDATE)
#define TO_SE_CMD_TLS_HANDLE_SERVER_KEY_EXCHANGE_FINAL   	    ((uint16_t)TO_CMD_ID_TLS_HANDLE_SERVER_KEY_EXCHANGE_FINAL)
#define TO_SE_CMD_TLS_HANDLE_CERTIFICATE_REQUEST 	            ((uint16_t)TO_CMD_ID_TLS_HANDLE_CERTIFICATE_REQUEST)
#define TO_SE_CMD_TLS_HANDLE_SERVER_HELLO_DONE 	                    ((uint16_t)TO_CMD_ID_TLS_HANDLE_SERVER_HELLO_DONE)
#define TO_SE_CMD_TLS_HANDLE_MEDIATOR_CERTIFICATE        	    ((uint16_t)TO_CMD_ID_TLS_HANDLE_MEDIATOR_CERTIFICATE)
#define TO_SE_CMD_TLS_GET_CERTIFICATE 	                            ((uint16_t)TO_CMD_ID_TLS_GET_CERTIFICATE)
#define TO_SE_CMD_TLS_GET_CERTIFICATE_INIT 	                    ((uint16_t)TO_CMD_ID_TLS_GET_CERTIFICATE_INIT)
#define TO_SE_CMD_TLS_GET_CERTIFICATE_UPDATE 	                    ((uint16_t)TO_CMD_ID_TLS_GET_CERTIFICATE_UPDATE)
#define TO_SE_CMD_TLS_GET_CERTIFICATE_FINAL 	                    ((uint16_t)TO_CMD_ID_TLS_GET_CERTIFICATE_FINAL)
#define TO_SE_CMD_TLS_GET_CLIENT_KEY_EXCHANGE 	                    ((uint16_t)TO_CMD_ID_TLS_GET_CLIENT_KEY_EXCHANGE)
#define TO_SE_CMD_TLS_GET_CERTIFICATE_VERIFY 	                    ((uint16_t)TO_CMD_ID_TLS_GET_CERTIFICATE_VERIFY)
#define TO_SE_CMD_TLS_GET_CHANGE_CIPHER_SPEC 	                    ((uint16_t)TO_CMD_ID_TLS_GET_CHANGE_CIPHER_SPEC)
#define TO_SE_CMD_TLS_GET_MASTER_SECRET_DERIVED_KEYS     	    ((uint16_t)TO_CMD_ID_TLS_GET_MASTER_SECRET_DERIVED_KEYS)
#define TO_SE_CMD_TLS_GET_FINISHED 	                            ((uint16_t)TO_CMD_ID_TLS_GET_FINISHED)
#define TO_SE_CMD_TLS_HANDLE_CHANGE_CIPHER_SPEC 	            ((uint16_t)TO_CMD_ID_TLS_HANDLE_CHANGE_CIPHER_SPEC)
#define TO_SE_CMD_TLS_HANDLE_FINISHED 	                            ((uint16_t)TO_CMD_ID_TLS_HANDLE_FINISHED)
#define TO_SE_CMD_TLS_GET_CERTIFICATE_SLOT               	    ((uint16_t)TO_CMD_ID_TLS_GET_CERTIFICATE_SLOT)
#define TO_SE_CMD_TLS_SECURE_MESSAGE 	                            ((uint16_t)TO_CMD_ID_TLS_SECURE_MESSAGE)
#define TO_SE_CMD_TLS_SECURE_MESSAGE_INIT 	                    ((uint16_t)TO_CMD_ID_TLS_SECURE_MESSAGE_INIT)
#define TO_SE_CMD_TLS_SECURE_MESSAGE_UPDATE 	                    ((uint16_t)TO_CMD_ID_TLS_SECURE_MESSAGE_UPDATE)
#define TO_SE_CMD_TLS_SECURE_MESSAGE_FINAL 	                    ((uint16_t)TO_CMD_ID_TLS_SECURE_MESSAGE_FINAL)
#define TO_SE_CMD_TLS_UNSECURE_MESSAGE 	                            ((uint16_t)TO_CMD_ID_TLS_UNSECURE_MESSAGE)
#define TO_SE_CMD_TLS_UNSECURE_MESSAGE_INIT 	                    ((uint16_t)TO_CMD_ID_TLS_UNSECURE_MESSAGE_INIT)
#define TO_SE_CMD_TLS_UNSECURE_MESSAGE_UPDATE 	                    ((uint16_t)TO_CMD_ID_TLS_UNSECURE_MESSAGE_UPDATE)
#define TO_SE_CMD_TLS_UNSECURE_MESSAGE_FINAL 	                    ((uint16_t)TO_CMD_ID_TLS_UNSECURE_MESSAGE_FINAL)
#define TO_SE_CMD_TLS_GET_RANDOM_AND_STORE                          ((uint16_t)TO_CMD_ID_TLS_GET_RANDOM_AND_STORE)
#define TO_SE_CMD_TLS_RENEW_KEYS                                    ((uint16_t)TO_CMD_ID_TLS_RENEW_KEYS)
#define TO_SE_CMD_TLS_GET_MASTER_SECRET                             ((uint16_t)TO_CMD_ID_TLS_GET_MASTER_SECRET)
#define TO_SE_CMD_TLS_SET_SERVER_RANDOM                             ((uint16_t)TO_CMD_ID_TLS_SET_SERVER_RANDOM)
#define TO_SE_CMD_TLS_SET_SERVER_EPUBLIC_KEY                        ((uint16_t)TO_CMD_ID_TLS_SET_SERVER_EPUBLIC_KEY)
#define TO_SE_CMD_TLS_RENEW_KEYS_ECDHE                              ((uint16_t)TO_CMD_ID_TLS_RENEW_KEYS_ECDHE)
#define TO_SE_CMD_TLS_CALCULATE_FINISHED                            ((uint16_t)TO_CMD_ID_TLS_CALCULATE_FINISHED)
#define TO_SE_CMD_TLS_GET_CLIENT_HELLO_INIT                         ((uint16_t)TO_CMD_ID_TLS_GET_CLIENT_HELLO_INIT)
#define TO_SE_CMD_TLS_GET_CLIENT_HELLO_UPDATE                       ((uint16_t)TO_CMD_ID_TLS_GET_CLIENT_HELLO_UPDATE)
#define TO_SE_CMD_TLS_GET_CLIENT_HELLO_FINAL                        ((uint16_t)TO_CMD_ID_TLS_GET_CLIENT_HELLO_FINAL)
#define TO_SE_CMD_GET_TLS_MASTER_SECRET 	                    ((uint16_t)TO_CMD_ID_GET_TLS_MASTER_SECRET)

/* Secure messaging */
#define TO_SE_CMD_SECURE_MESSAGE 		                    ((uint16_t)TO_CMD_ID_SECURE_MESSAGE)
#define TO_SE_CMD_SECURE_MESSAGE_INIT 		                    ((uint16_t)TO_CMD_ID_SECURE_MESSAGE_INIT)
#define TO_SE_CMD_SECURE_MESSAGE_UPDATE 		            ((uint16_t)TO_CMD_ID_SECURE_MESSAGE_UPDATE)
#define TO_SE_CMD_SECURE_MESSAGE_FINAL 		                    ((uint16_t)TO_CMD_ID_SECURE_MESSAGE_FINAL)
#define TO_SE_CMD_UNSECURE_MESSAGE 		                    ((uint16_t)TO_CMD_ID_UNSECURE_MESSAGE)
#define TO_SE_CMD_UNSECURE_MESSAGE_INIT 		            ((uint16_t)TO_CMD_ID_UNSECURE_MESSAGE_INIT)
#define TO_SE_CMD_UNSECURE_MESSAGE_UPDATE 		            ((uint16_t)TO_CMD_ID_UNSECURE_MESSAGE_UPDATE)
#define TO_SE_CMD_UNSECURE_MESSAGE_FINAL 		            ((uint16_t)TO_CMD_ID_UNSECURE_MESSAGE_FINAL)

/* LoRa */
#define TO_SE_CMD_LORA_GET_APPEUI 		                    ((uint16_t)TO_CMD_ID_LORA_GET_APPEUI)
#define TO_SE_CMD_LORA_GET_DEVEUI 		                    ((uint16_t)TO_CMD_ID_LORA_GET_DEVEUI)
#define TO_SE_CMD_LORA_COMPUTE_MIC 		                    ((uint16_t)TO_CMD_ID_LORA_COMPUTE_MIC)
#define TO_SE_CMD_LORA_ENCRYPT_PAYLOAD 		                    ((uint16_t)TO_CMD_ID_LORA_ENCRYPT_PAYLOAD)
#define TO_SE_CMD_LORA_DECRYPT_JOIN 		                    ((uint16_t)TO_CMD_ID_LORA_DECRYPT_JOIN)
#define TO_SE_CMD_LORA_COMPUTE_SHARED_KEYS 		            ((uint16_t)TO_CMD_ID_LORA_COMPUTE_SHARED_KEYS)
#define TO_SE_CMD_LORA_GET_DEVADDR 		                    ((uint16_t)TO_CMD_ID_LORA_GET_DEVADDR)

/* LoRa optimized */
#define TO_SE_CMD_LORA_GET_JOIN_REQUEST 		            ((uint16_t)TO_CMD_ID_LORA_GET_JOIN_REQUEST)
#define TO_SE_CMD_LORA_HANDLE_JOIN_ACCEPT 		            ((uint16_t)TO_CMD_ID_LORA_HANDLE_JOIN_ACCEPT)
#define TO_SE_CMD_LORA_SECURE_PHYPAYLOAD 		            ((uint16_t)TO_CMD_ID_LORA_SECURE_PHYPAYLOAD)
#define TO_SE_CMD_LORA_UNSECURE_PHYPAYLOAD 		            ((uint16_t)TO_CMD_ID_LORA_UNSECURE_PHYPAYLOAD)

/* Personalization */
#define TO_SE_CMD_SET_PRE_PERSONALIZATION_DATA                      ((uint16_t)TO_CMD_ID_SET_PRE_PERSONALIZATION_DATA)
#define TO_SE_CMD_SET_NEXT_STATE 			            ((uint16_t)TO_CMD_ID_SET_NEXT_STATE)
#define TO_SE_CMD_GET_STATE 			                    ((uint16_t)TO_CMD_ID_GET_STATE)

/* Administration commands */
#define TO_SE_CMD_ADMIN_SET_SLOT 	                            ((uint16_t)TO_CMD_ID_ADMIN_SET_SLOT)
#define TO_SE_CMD_INIT_ADMIN_SESSION 	                            ((uint16_t)TO_CMD_ID_INIT_ADMIN_SESSION)
#define TO_SE_CMD_AUTH_ADMIN_SESSION 	                            ((uint16_t)TO_CMD_ID_AUTH_ADMIN_SESSION)
#define TO_SE_CMD_FINI_ADMIN_SESSION 	                            ((uint16_t)TO_CMD_ID_FINI_ADMIN_SESSION)
#define TO_SE_CMD_ADMIN_COMMAND 	                            ((uint16_t)TO_CMD_ID_ADMIN_COMMAND)
#define TO_SE_CMD_ADMIN_COMMAND_WITH_RESPONSE 	                    ((uint16_t)TO_CMD_ID_ADMIN_COMMAND_WITH_RESPONSE)

/* Lock */
#define TO_SE_CMD_LOCK 		                                    ((uint16_t)TO_CMD_ID_LOCK)
#define TO_SE_CMD_UNLOCK 		                            ((uint16_t)TO_CMD_ID_UNLOCK)

/* Symmetric key Management */
#define TO_SE_CMD_SET_AES_KEY 	                                    ((uint16_t)TO_CMD_ID_SET_AES_KEY)
#define TO_SE_CMD_SET_HMAC_KEY 	                                    ((uint16_t)TO_CMD_ID_SET_HMAC_KEY)
#define TO_SE_CMD_SET_CMAC_KEY 	                                    ((uint16_t)TO_CMD_ID_SET_CMAC_KEY)

/* Secure link */
#define TO_SE_CMD_SECLINK_ARC4	                                    ((uint16_t)TO_CMD_ID_SECLINK_ARC4)
#define TO_SE_CMD_SECLINK_ARC4_GET_IV	                            ((uint16_t)TO_CMD_ID_SECLINK_ARC4_GET_IV)
#define TO_SE_CMD_SECLINK_ARC4_GET_NEW_KEY	                    ((uint16_t)TO_CMD_ID_SECLINK_ARC4_GET_NEW_KEY)
#define TO_SE_CMD_SECLINK_AESHMAC	                            ((uint16_t)TO_CMD_ID_SECLINK_AESHMAC)
#define TO_SE_CMD_SECLINK_AESHMAC_GET_IV	                    ((uint16_t)TO_CMD_ID_SECLINK_AESHMAC_GET_IV)
#define TO_SE_CMD_SECLINK_AESHMAC_GET_NEW_KEYS	                    ((uint16_t)TO_CMD_ID_SECLINK_AESHMAC_GET_NEW_KEYS)

#define TO_SE_CMD_LOADER_BCAST_GET_INFO                             ((uint16_t)TO_CMD_ID_LOADER_BCAST_GET_INFO)
#define TO_SE_CMD_LOADER_BCAST_INITIALIZE_UPGRADE                   ((uint16_t)TO_CMD_ID_LOADER_BCAST_INITIALIZE_UPGRADE)
#define TO_SE_CMD_LOADER_BCAST_WRITE_DATA                           ((uint16_t)TO_CMD_ID_LOADER_BCAST_WRITE_DATA)
#define TO_SE_CMD_LOADER_BCAST_COMMIT_RELEASE                       ((uint16_t)TO_CMD_ID_LOADER_BCAST_COMMIT_RELEASE)
#define TO_SE_CMD_DATA_MIGRATION                                    ((uint16_t)TO_CMD_ID_DATA_MIGRATION)
#define TO_SE_CMD_SET_MEASURE_BOOT                                  ((uint16_t)TO_CMD_ID_SET_MEASURE_BOOT)
#define TO_SE_CMD_VALIDATE_NEW_FW_HASH                              ((uint16_t)TO_CMD_ID_VALIDATE_NEW_FW_HASH)
#define TO_SE_CMD_COMMIT_NEW_FW_HASH                                ((uint16_t)TO_CMD_ID_COMMIT_NEW_FW_HASH)
#define TO_SE_CMD_STORE_NEW_TRUSTED_FW_HASH                         ((uint16_t)TO_CMD_ID_STORE_NEW_TRUSTED_FW_HASH)
#define TO_SE_CMD_GET_BOOT_MEASUREMENT                              ((uint16_t)TO_CMD_ID_GET_BOOT_MEASUREMENT)
#define TO_SE_CMD_GET_SE_MEASUREMENT                                ((uint16_t)TO_CMD_ID_GET_SE_MEASUREMENT)
#define TO_SE_CMD_LOADER_BCAST_RESTORE                              ((uint16_t)TO_CMD_ID_LOADER_BCAST_RESTORE)
#define TO_SE_CMD_INVALIDATE_NEW_HASH                               ((uint16_t)TO_CMD_ID_INVALIDATE_NEW_HASH)

#endif // _TO_CMDS_IDENTIFIERS_H_